# Generated by Django 3.0.4 on 2020-03-19 22:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import offers.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('afternoon', models.BooleanField(default=False, verbose_name='Nachmittags')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('evening', models.BooleanField(default=False, verbose_name='Abends')),
                ('morning', models.BooleanField(default=False, verbose_name='Morgens')),
                ('noon', models.BooleanField(default=False, verbose_name='Mittags')),
            ],
            options={
                'verbose_name': 'Hilfsangebot',
                'verbose_name_plural': 'Hilfsangebote',
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326)),
                ('radius', models.IntegerField(choices=[(1000, '1 km'), (2000, '2 km'), (3000, '3 km'), (4000, '4 km'), (5000, '5 km'), (10000, '10 km'), (20000, '20 km'), (50000, '50 km')], default=2000, verbose_name='Umkreis (nicht öffentlich)')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adresse (Straße, Stadt. Nicht öffentlich)')),
                ('mobility', models.TextField(choices=[('NA', 'keine Angabe'), ('FOOT', 'zu Fuß / ÖPNV'), ('BIKE', 'Fahrrad'), ('MOTOR_SCOOTER', 'Motorroller'), ('CAR', 'Auto')], default='NA', verbose_name='Fortbewegungsmittel (öffentlich sichtbar)')),
                ('comment', models.TextField(blank=True, verbose_name='Sonstige Hilfestellungen oder Kommentare')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer')),
                ('show_email', models.BooleanField(default=False, verbose_name='E-Mail-Adresse öffentlich anzeigen')),
                ('show_phone', models.BooleanField(default=False, verbose_name='Telefonnummer öffentlich anzeigen')),
                ('offers_fetching_drugs', models.BooleanField(default=False, verbose_name='Medikamente abholen')),
                ('offers_petsitting', models.BooleanField(default=False, verbose_name='Gassi gehen')),
                ('offers_sending_mail', models.BooleanField(default=False, verbose_name='Briefe einwerfen')),
                ('offers_shopping', models.BooleanField(default=False, verbose_name='Einkaufen')),
                ('offers_courier', models.BooleanField(default=False, verbose_name='Kurierdienste')),
                ('gender', models.CharField(choices=[('M', 'Männlich'), ('F', 'Weiblich'), ('D', 'Andere'), ('X', 'Keine Angabe')], default='X', max_length=50, verbose_name='Geschlecht')),
                ('show_gender', models.BooleanField(default=False, verbose_name='Geschlecht öffentlich anzeigen')),
                ('name_visibility', models.CharField(choices=[('FULL', 'Vor- und Nachname öffentlich'), ('FIRST_NAME', 'Nur Vorname öffentlich'), ('HIDDEN', 'Weder Vor- noch Nachname öffentlich')], default='FIRST_NAME', max_length=50, verbose_name='Öffentlichkeit deines Namens')),
                ('activation_token', models.CharField(default=offers.helper.create_activation_token, max_length=64, verbose_name='Aktivierungsschlüssel')),
                ('activated', models.BooleanField(default=False, verbose_name='Aktiviert')),
            ],
            options={
                'verbose_name': 'Anbieterprofil',
                'verbose_name_plural': 'Anbieterprofile',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('sender_email', models.CharField(blank=True, max_length=100)),
                ('sender_phone', models.CharField(blank=True, max_length=100)),
                ('sender_gender', models.CharField(choices=[('M', 'Männlich'), ('F', 'Weiblich'), ('D', 'Andere'), ('X', 'Keine Angabe')], default='X', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gesendete Nachricht',
                'verbose_name_plural': 'Gesendete Nachrichten',
            },
        ),
    ]
