# Generated by Django 3.0.4 on 2020-03-19 22:52

from django.db import migrations, models
import offers.helper


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='slug',
            field=models.CharField(default=offers.helper.create_profile_slug, max_length=20, unique=True, verbose_name='ID-Token'),
        ),
    ]
