# Generated by Django 3.0.4 on 2020-03-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_providerprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_gender',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='show_gender',
        ),
    ]
