# Generated by Django 3.0.4 on 2020-03-16 18:06

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0002_auto_20200316_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='mobility',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='radius',
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('radius', models.IntegerField(choices=[(1000, '1 km'), (2000, '2 km'), (3000, '3 km'), (4000, '4 km'), (5000, '5 km'), (10000, '10 km'), (20000, '20 km'), (50000, '50 km')], default=2000, verbose_name='Umkreis')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Adresse (Straße, Hausnummer)')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('mobility', models.TextField(choices=[('NA', 'keine Angabe'), ('FOOT', 'zu Fuß / ÖPNV'), ('BIKE', 'Fahrrad'), ('MOTOR_SCOOTER', 'Motorroller'), ('CAR', 'Auto')], default='NA', verbose_name='Fortbewegungsmittel')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anbieterprofil',
                'verbose_name_plural': 'Anbieterprofile',
            },
        ),
    ]
