# Generated by Django 3.0.4 on 2020-03-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20200316_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='E-Mail-Adresse öffentlich anzeigen'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='show_phone',
            field=models.BooleanField(default=False, verbose_name='Telefonnummer öffentlich anzeigen'),
        ),
    ]
