# Generated by Django 3.0.4 on 2020-03-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20200323_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stadt (nicht öffentlich)'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße (nicht öffentlich)'),
        ),
    ]
