# Generated by Django 3.0.4 on 2020-03-23 14:25

from django.db import migrations
from django.db.migrations import RunPython


def split_address(apps, schema_editor):
    ProviderProfile = apps.get_model('offers', 'ProviderProfile')

    for profile in ProviderProfile.objects.all():
        if len(profile.address.split(", ")) > 1:
            profile.street = ", ".join(profile.address.split(", ")[:-1])
            profile.city = profile.address.split(", ")[-1]
        else:
            profile.street = profile.address
            profile.city = ''
        profile.save()


def reverse_split_address(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20200323_1424'),
    ]

    operations = [
        RunPython(split_address, reverse_split_address)
    ]
