# Generated by Django 3.0.4 on 2020-03-16 19:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20200316_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
    ]
