# Generated by Django 3.0.4 on 2020-03-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20200316_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='offers_fetching_drugs',
            field=models.BooleanField(default=False, verbose_name='Medikamente abholen'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='offers_petsitting',
            field=models.BooleanField(default=False, verbose_name='Gassi gehen'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='offers_removing_trash',
            field=models.BooleanField(default=False, verbose_name='Müll wegbringen'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='offers_sending_mail',
            field=models.BooleanField(default=False, verbose_name='Briefe einwerfen'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='offers_shopping',
            field=models.BooleanField(default=False, verbose_name='Einkaufen'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Sonstige Hilfestellungen oder Kommentare'),
        ),
    ]
