# Generated by Django 3.0.4 on 2020-03-23 14:40

from django.db import migrations
from django.db.migrations import RunPython


def remove_phone_where_it_is_not_public(apps, schema_editor):
    ProviderProfile = apps.get_model('offers', 'ProviderProfile')

    for profile in ProviderProfile.objects.all():
        if not profile.show_phone:
            profile.phone = ''
            profile.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_split_address_into_street_and_city'),
    ]

    operations = [
        RunPython(remove_phone_where_it_is_not_public, reverse)
    ]
