# Generated by Django 3.0.4 on 2020-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_remove_phone_number_if_it_is_not_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Sonstige Hilfestellungen oder Kommentare (öffentlich)'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer (öffentlich wenn du sie angibst)'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='show_phone',
            field=models.BooleanField(default=False),
        ),
    ]
