# Generated by Django 3.0.4 on 2020-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20200317_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='afternoon',
            field=models.BooleanField(default=True, verbose_name='Nachmittags'),
        ),
    ]
