# Generated by Django 3.0.4 on 2020-03-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20200323_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='show_phone',
        ),
    ]
