# Generated by Django 3.0.4 on 2020-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_auto_20200317_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='offers_removing_trash',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='offers_courier',
            field=models.BooleanField(default=False, verbose_name='Kurierdienste'),
        ),
    ]
