# Generated by Django 3.0.4 on 2020-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_remove_providerprofile_show_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Anzeigename (öffentlich)'),
        ),
    ]
