# Generated by Django 3.0.4 on 2020-03-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20200317_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='city',
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse (Straße, Hausnummer, Stadt)'),
        ),
    ]
