# Generated by Django 3.0.4 on 2020-03-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_fill_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='name_visibility',
        ),
    ]
