# Generated by Django 3.0.4 on 2020-03-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_auto_20200317_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Männlich'), ('F', 'Weiblich'), ('D', 'Andere'), ('X', 'Keine Angabe')], default='X', max_length=50, verbose_name='Geschlecht'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='show_gender',
            field=models.BooleanField(default=False, verbose_name='Geschlecht öffentlich anzeigen'),
        ),
    ]
