# Generated by Django 3.0.4 on 2020-03-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_auto_20200317_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='name_visibility',
            field=models.CharField(choices=[('FULL', 'Vor- und Nachname öffentlich'), ('FIRST_NAME', 'Nur Vorname öffentlich'), ('HIDDEN', 'Weder Vor- noch Nachname öffentlich')], default='FIRST_NAME', max_length=50, verbose_name='Öffentlichkeit deines Namens'),
        ),
    ]
