# Generated by Django 3.0.4 on 2020-03-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_remove_providerprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='mobility',
            field=models.TextField(choices=[('NA', 'keine Angabe'), ('FOOT', 'zu Fuß / ÖPNV'), ('BIKE', 'Fahrrad'), ('MOTOR_SCOOTER', 'Motorroller'), ('CAR', 'Auto')], default='NA', verbose_name='Fortbewegungsmittel (öffentlich)'),
        ),
    ]
