# Generated by Django 3.0.4 on 2020-03-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_auto_20200323_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HOME', 'Startseite'), ('SAFETY', 'Sicherheits-Informationen'), ('IMPRINT', 'Impressum'), ('PRIVACY', 'Datenschutz')], max_length=100)),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=100)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webseiten-Inhalt',
                'verbose_name_plural': 'Webseiten-Inhalte',
                'unique_together': {('name', 'language')},
            },
        ),
    ]
