# Generated by Django 3.0.4 on 2020-03-18 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0014_auto_20200318_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('sender_email', models.CharField(blank=True, max_length=100)),
                ('sender_phone', models.CharField(blank=True, max_length=100)),
                ('sender_gender', models.CharField(choices=[('M', 'Männlich'), ('F', 'Weiblich'), ('D', 'Andere'), ('X', 'Keine Angabe')], default='X', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
