# Generated by Django 3.0.4 on 2020-03-19 14:43

from django.db import migrations, models
import offers.helper


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Sent Message', 'verbose_name_plural': 'Sent Messages'},
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='activation_token',
            field=models.CharField(default=offers.helper.create_activation_token, max_length=64, verbose_name='Aktivierungsschlüssel'),
        ),
    ]
