# Generated by Django 3.0.4 on 2020-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_auto_20200319_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Aktiviert'),
        ),
    ]
