# Generated by Django 3.0.4 on 2020-03-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_providerprofile_activated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Gesendete Nachricht', 'verbose_name_plural': 'Gesendete Nachrichten'},
        ),
    ]
