# Generated by Django 3.0.4 on 2020-03-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_auto_20200319_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Sent Message', 'verbose_name_plural': 'Sent Messages'},
        ),
    ]
