# Generated by Django 3.0.4 on 2020-03-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_auto_20200319_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Gesendete Nachricht', 'verbose_name_plural': 'Gesendete Nachrichten'},
        ),
    ]
